/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationDetail {
  'id' : ConversationId,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ConversationId = bigint;
export interface ConversationSummary {
  'id' : ConversationId,
  'title' : string,
  'lastMessagePreview' : [] | [string],
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings { 'aiEndpoint' : string }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<[string], ConversationSummary>,
  'deleteConversation' : ActorMethod<[ConversationId], boolean>,
  'getCallerSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[ConversationId], [] | [ConversationDetail]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'renameConversation' : ActorMethod<[ConversationId, string], boolean>,
  'saveCallerSettings' : ActorMethod<[UserSettings], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ConversationId, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];