/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'lastMessagePreview' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const UserSettings = IDL.Record({ 'aiEndpoint' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MessageId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const ConversationDetail = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Text], [ConversationSummary], []),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'getCallerSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(ConversationDetail)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'renameConversation' : IDL.Func([ConversationId, IDL.Text], [IDL.Bool], []),
  'saveCallerSettings' : IDL.Func([UserSettings], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'lastMessagePreview' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const UserSettings = IDL.Record({ 'aiEndpoint' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MessageId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const ConversationDetail = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Text], [ConversationSummary], []),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'getCallerSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(ConversationDetail)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'renameConversation' : IDL.Func([ConversationId, IDL.Text], [IDL.Bool], []),
    'saveCallerSettings' : IDL.Func([UserSettings], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };